/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectofinal;

/**
 *
 * @author Jose Sisay
 */

import javax.swing.table.DefaultTableModel;
import java.io.*;
import java.util.Scanner;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
public class RegistroVehiculos extends javax.swing.JFrame {
    ListaVehiculos lista = new ListaVehiculos();
  ListaVehiculosAVL listaAvl = new ListaVehiculosAVL();

    /**
     * Creates new form RegistroVehiculos
     */
    public RegistroVehiculos() {
        
        initComponents();
              
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Placa = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        DPI = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        Propietario = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        MarcaVehiculo = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        Modelo = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        Año = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        RadioABB = new javax.swing.JRadioButton();
        RadioAVL = new javax.swing.JRadioButton();
        InsertarRegistros = new javax.swing.JButton();
        BuscarRegistro = new javax.swing.JButton();
        Eliminar = new javax.swing.JButton();
        Guarddar = new javax.swing.JButton();
        Modificar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        LimpiarTabla = new javax.swing.JButton();
        Departamentos = new javax.swing.JLabel();
        CargarArchivo = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        LimpiarTablaAVL = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 255, 204));

        jPanel1.setBackground(new java.awt.Color(0, 255, 255));
        jPanel1.setForeground(new java.awt.Color(102, 0, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("REGISTRO DE VEHICULOS ING SISAY :)");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 0, 224, 33));

        Placa.setText("Placa");
        jPanel1.add(Placa, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 42, 37, -1));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 39, 130, -1));

        DPI.setText("DPI");
        jPanel1.add(DPI, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 42, -1, -1));
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 39, 150, -1));

        Propietario.setText("Propietario");
        jPanel1.add(Propietario, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 82, 71, -1));
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 79, 190, -1));

        MarcaVehiculo.setText("Marca Vehiculo");
        jPanel1.add(MarcaVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 90, 101, -1));
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, 130, -1));

        Modelo.setText("Modelo");
        jPanel1.add(Modelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 69, -1));
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 150, -1));

        Año.setText("Año");
        jPanel1.add(Año, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 37, -1));
        jPanel1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 71, -1));
        jPanel1.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 71, -1));
        jPanel1.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, 71, -1));

        RadioABB.setText("Arbol ABB");
        RadioABB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioABBActionPerformed(evt);
            }
        });
        jPanel1.add(RadioABB, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 210, 98, -1));

        RadioAVL.setText("Arbol AVL");
        RadioAVL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioAVLActionPerformed(evt);
            }
        });
        jPanel1.add(RadioAVL, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 460, 98, -1));

        InsertarRegistros.setText("Insertar");
        InsertarRegistros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertarRegistrosActionPerformed(evt);
            }
        });
        jPanel1.add(InsertarRegistros, new org.netbeans.lib.awtextra.AbsoluteConstraints(745, 15, 100, 40));

        BuscarRegistro.setText("Buscar Registro");
        BuscarRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarRegistroActionPerformed(evt);
            }
        });
        jPanel1.add(BuscarRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 30, 120, 40));

        Eliminar.setText("Eliminar ");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });
        jPanel1.add(Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(745, 79, 100, 40));

        Guarddar.setText("Guardar");
        Guarddar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuarddarActionPerformed(evt);
            }
        });
        jPanel1.add(Guarddar, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 140, 110, 50));

        Modificar.setText("Modificar");
        Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarActionPerformed(evt);
            }
        });
        jPanel1.add(Modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 90, 90, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Placa", "DPI", "Propietario", "MarcaVehiculos", "Modelo", "Año", "Multa", "Traspaso"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 651, 161));

        jScrollPane2.setViewportView(jList1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 240, 170, 180));

        LimpiarTabla.setText("Limpiar Tabla");
        LimpiarTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarTablaActionPerformed(evt);
            }
        });
        jPanel1.add(LimpiarTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 420, 136, 46));

        Departamentos.setText("DEPARTAMENTOS");
        jPanel1.add(Departamentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 420, 155, -1));

        CargarArchivo.setText("Cargar Archivos");
        CargarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargarArchivoActionPerformed(evt);
            }
        });
        jPanel1.add(CargarArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 120, 30));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Antigua_Guatemala", "Chimaltenango", "Chiquimula", "Escuintla", "Guatemala", "Huehuetenango", "Peten", "Quetzaltenango", "San_Marcos", "Suchitepequez", " " }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 450, 150, 30));

        jLabel2.setText("Multas");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, -1, -1));

        jLabel3.setText("Traspaso");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, -1, -1));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Placa", "DPI", "Propietario", "MarcaVehiculo", "Modelo", "Año", "Multa", "Traspaso"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, 650, 170));

        jScrollPane4.setViewportView(jList2);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 490, 170, 180));

        LimpiarTablaAVL.setText("Limpiar Tabla AVL");
        LimpiarTablaAVL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarTablaAVLActionPerformed(evt);
            }
        });
        jPanel1.add(LimpiarTablaAVL, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 710, 140, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 884, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 814, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BuscarRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarRegistroActionPerformed
       
   String departamento = jComboBox1.getSelectedItem().toString();

    // ABB
    DefaultTableModel modeloABB = (DefaultTableModel) jTable1.getModel();
    modeloABB.setRowCount(0);
    lista.buscarVehiculo(modeloABB, departamento,
        jTextField1.getText(),
        jTextField2.getText(),
        jTextField3.getText(),
        jTextField4.getText(),
        jTextField5.getText(),
        jTextField6.getText());

    // AVL
    DefaultTableModel modeloAVL = (DefaultTableModel) jTable2.getModel();
    modeloAVL.setRowCount(0);
    listaAvl.buscarVehiculo(modeloAVL, departamento,
        jTextField1.getText(),
        jTextField2.getText(),
        jTextField3.getText(),
        jTextField4.getText(),
        jTextField5.getText(),
        jTextField6.getText());

    if (modeloABB.getRowCount() == 0 && modeloAVL.getRowCount() == 0) {
        JOptionPane.showMessageDialog(this, "Elemento no encontrado, verifique los datos ingresados.", "Sin resultados", JOptionPane.WARNING_MESSAGE);
    }
    }//GEN-LAST:event_BuscarRegistroActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void CargarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargarArchivoActionPerformed
    String departamento = jComboBox1.getSelectedItem().toString();
    lista.cargarDesdeArchivo((DefaultTableModel) jTable1.getModel(), departamento);
    
    
    lista.cargarDesdeArchivo((DefaultTableModel) jTable2.getModel(), departamento);
    
    
    }//GEN-LAST:event_CargarArchivoActionPerformed

    private void LimpiarTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarTablaActionPerformed
    DefaultTableModel modeloTabla = (DefaultTableModel) jTable1.getModel();
    modeloTabla.setRowCount(0);
    }//GEN-LAST:event_LimpiarTablaActionPerformed

    private void InsertarRegistrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertarRegistrosActionPerformed
DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();

    String[] nuevo = new String[]{
        jTextField1.getText(),
        jTextField2.getText(),
        jTextField3.getText(),
        jTextField4.getText(),
        jTextField5.getText(),
        jTextField6.getText(),
        jTextField7.getText(),
        jTextField8.getText()
    };

    lista.insertarDesdeCampos(modelo, nuevo);
    JOptionPane.showMessageDialog(this, "✅ Registro preparado. Presione GUARDAR para agregarlo al archivo.");
    }//GEN-LAST:event_InsertarRegistrosActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
   int fila = jTable1.getSelectedRow();
if (fila != -1) {
    lista.eliminarFila((DefaultTableModel) jTable1.getModel(), fila);
    JOptionPane.showMessageDialog(this, "✅ Fila eliminada. Recuerda presionar GUARDAR.");
} else {
    JOptionPane.showMessageDialog(this, "❌ Selecciona una fila para eliminar.");
    }
    }//GEN-LAST:event_EliminarActionPerformed

    private void GuarddarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuarddarActionPerformed
                                                
          String depto = jComboBox1.getSelectedItem().toString();
lista.guardarEnArchivo((DefaultTableModel) jTable1.getModel(), depto);
    }//GEN-LAST:event_GuarddarActionPerformed

    private void ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarActionPerformed
                                         
  int fila = jTable1.getSelectedRow();
    if (fila == -1) {
        JOptionPane.showMessageDialog(this, "❌ Seleccione una fila para modificar.");
    } else {
        String[] nuevosDatos = new String[8];
        for (int j = 0; j < 8; j++) {
            nuevosDatos[j] = jTable1.getValueAt(fila, j).toString();
        }
        lista.modificarFila((DefaultTableModel) jTable1.getModel(), fila, nuevosDatos);
    }
    }//GEN-LAST:event_ModificarActionPerformed

    private void RadioABBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioABBActionPerformed
          ArbolABB abb = new ArbolABB(); // Crear nueva instancia del árbol
    DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel(); // Obtener el modelo actual de la tabla
    DefaultListModel<String> tiempos = abb.medirTiemposDesdeTabla(modelo); // Medir los tiempos

    jList1.setModel(tiempos); // Mostrar los tiempos en el JList
    }//GEN-LAST:event_RadioABBActionPerformed

    private void RadioAVLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioAVLActionPerformed
       ArbolAVL avl = new ArbolAVL();
DefaultTableModel modelo2 = (DefaultTableModel) jTable2.getModel();
DefaultListModel<String> tiemposAVL = avl.medirTiemposDesdeTabla(modelo2);
jList2.setModel(tiemposAVL);
    }//GEN-LAST:event_RadioAVLActionPerformed

    private void LimpiarTablaAVLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarTablaAVLActionPerformed
        DefaultTableModel modeloTabla = (DefaultTableModel) jTable2.getModel();
    modeloTabla.setRowCount(0);
    }//GEN-LAST:event_LimpiarTablaAVLActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroVehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroVehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroVehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroVehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroVehiculos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Año;
    private javax.swing.JButton BuscarRegistro;
    private javax.swing.JButton CargarArchivo;
    private javax.swing.JLabel DPI;
    private javax.swing.JLabel Departamentos;
    private javax.swing.JButton Eliminar;
    private javax.swing.JButton Guarddar;
    private javax.swing.JButton InsertarRegistros;
    private javax.swing.JButton LimpiarTabla;
    private javax.swing.JButton LimpiarTablaAVL;
    private javax.swing.JLabel MarcaVehiculo;
    private javax.swing.JLabel Modelo;
    private javax.swing.JButton Modificar;
    private javax.swing.JLabel Placa;
    private javax.swing.JLabel Propietario;
    private javax.swing.JRadioButton RadioABB;
    private javax.swing.JRadioButton RadioAVL;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
